### ISSUE TITLE
Capture image causes NullPointerExceotion on SamSung Glaxy S4

### ISSUE THREAD

**Issue by HeyCoff** [sd6352051/android-image-picker#1]
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.io.File.getAbsolutePath()' on a null object reference
                                                                              at com.litao.android.lib.GalleryFragment.onActivityResult(GalleryFragment.java:261)
                                                                              at android.app.Activity.dispatchActivityResult(Activity.java:6553)
                                                                              at android.app.ActivityThread.deliverResults(ActivityThread.java:4054)
                                                                              at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3380) 
                                                                              at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3425) 
                                                                              at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2763) 
                                                                              at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4462) 
                                                                              at android.app.ActivityThread.access$1000(ActivityThread.java:177) 
                                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1454) 
                                                                              at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                              at android.os.Looper.loop(Looper.java:145)

**Comment by litao0621** [comment]
hi @HeyCoff 
Could you pls paste your java code snippet?

**Comment by HeyCoff** [comment]
Add "android:configChanges='orientation|keyboardHidden|screenSize'" to activity manifest then the problem was been solved, thank you

**Comment by litao0621** [comment]
cool ! 👍  
closed
